import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');
const styleGuidePath = join(repoRoot, 'assets-src/yoyo/v3/style-guide.json');
const promptPackPath = join(repoRoot, 'assets-src/yoyo/v3/prompt-pack.json');
const manifestPath = join(repoRoot, 'assets-src/yoyo/v3/manifest.json');
const runtimeManifestPath = join(repoRoot, 'assets/yoyo/pack-manifest.json');
const qaReportPath = join(repoRoot, 'assets/yoyo/qa/v3/v3-kit-report.md');

function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

describe('Yoyo V3 full asset kit contract', () => {
  test('defines a coherent V3 style guide and prompt pack', () => {
    const styleGuide = readJson(styleGuidePath);
    const promptPack = readJson(promptPackPath);

    assert.equal(styleGuide.id, 'yoyo-v3');
    assert.equal(styleGuide.character.identity, 'human-like little-girl desktop companion');
    assert.equal(styleGuide.character.runtimeDriver, 'pixi-spritesheet-compat');
    assert.match(styleGuide.character.description, /3-5 year old/u);
    assert.match(styleGuide.character.description, /short childlike limbs/u);
    assert.deepEqual(styleGuide.rooms.size, { width: 1272, height: 720 });
    assert.ok(styleGuide.avoid.includes('dog bowl'));
    assert.ok(styleGuide.avoid.includes('kibble'));
    assert.ok(styleGuide.avoid.includes('paw motif'));
    assert.ok(styleGuide.mustPreserve.includes('warm v3-safe Yoyo nook mood'));

    const promptIds = new Set(promptPack.prompts.map((prompt) => prompt.id));
    assert.ok(
      promptPack.sourceReferences.includes('assets-src/yoyo/reference/rig/yoyo-standing-clean2d-v3-alpha.png'),
      'prompt pack should use the user-approved V3 character reference',
    );
    for (const id of [
      'room-v3-day',
      'room-v3-night',
      'room-v3-rainy',
      'room-v3-party',
      'prop-v3-meal-table',
      'prop-v3-bed',
      'prop-v3-wash-stand',
      'prop-v3-study-desk',
      'composite-v3-feed',
      'composite-v3-sleep',
      'character-rig-v3-source',
    ]) {
      assert.ok(promptIds.has(id), `missing prompt ${id}`);
    }
  });

  test('maps every V3 source asset to a runtime asset and QA evidence', () => {
    const manifest = readJson(manifestPath);

    assert.equal(manifest.id, 'yoyo-v3-full-asset-kit');
    assert.equal(manifest.runtimeCompatibility.avatarDriver, 'pixi-spritesheet');
    assert.equal(manifest.runtimeCompatibility.keepCurrentSpritesheet, true);
    assert.equal(manifest.rooms.length, 4);
    assert.ok(
      manifest.rooms.every((asset) => asset.runtime.endsWith('-safe.webp') && asset.width === 1272 && asset.height === 720),
      'V3 room runtimes should point to the no-dog-bowl safe room derivatives',
    );
    assert.equal(manifest.props.length, 9);
    assert.equal(manifest.composites.length, 5);

    for (const group of ['rooms', 'props', 'composites']) {
      for (const asset of manifest[group]) {
        assert.ok(asset.id.startsWith(`${group.slice(0, -1)}-v3-`) || asset.id.startsWith('composite-v3-'));
        assert.ok(asset.source.startsWith('assets-src/yoyo/v3/'), `${asset.id} source must live in v3 sources`);
        assert.ok(asset.runtime.startsWith('assets/yoyo/home/'), `${asset.id} runtime asset must be packaged under home`);
        assert.ok(asset.qaPreview.startsWith('assets/yoyo/qa/v3/'), `${asset.id} needs V3 QA evidence`);
      }
    }
  });

  test('runtime manifest registers V3 without removing spritesheet compatibility', () => {
    const runtimeManifest = readJson(runtimeManifestPath);

    assert.equal(runtimeManifest.avatar.driver, 'pixi-spritesheet');
    assert.equal(runtimeManifest.avatar.sheet, 'spritesheet.webp');
    assert.equal(runtimeManifest.v3.active, true);
    assert.equal(runtimeManifest.v3.rooms.day, 'home/room-v3-day-safe.webp');
    assert.equal(runtimeManifest.v3.props.feed, 'home/prop-v3-meal-table.webp');
    assert.deepEqual(runtimeManifest.v3.composites, {});
    assert.equal(runtimeManifest.careScenes.sleep.prop, 'home/prop-v3-bed.webp');
  });

  test('V3 audit report exists after the audit command runs', () => {
    assert.ok(existsSync(qaReportPath), 'V3 QA report should be generated by scripts/audit-yoyo-v3-kit.js');
    const report = readFileSync(qaReportPath, 'utf8');
    assert.match(report, /# Yoyo V3 Full Asset Kit QA Report/u);
    assert.match(report, /Spritesheet Compatibility/u);
    assert.match(report, /Runtime Captures/u);
    assert.match(report, /Expression Controls/u);
    assert.match(report, /Presets: 11/u);
  });

  test('defines the next character rig contract without replacing the current spritesheet', () => {
    const manifest = readJson(manifestPath);
    const rigContract = readJson(join(repoRoot, manifest.characterRig.contract));

    assert.equal(manifest.runtimeCompatibility.keepCurrentSpritesheet, true);
    assert.equal(manifest.characterRig.runtimeStatus, 'experimental');
    assert.equal(rigContract.id, 'yoyo-v3-character-rig-contract');
    assert.equal(rigContract.currentRuntime, 'pixi-spritesheet');
    assert.equal(rigContract.nextRuntime, 'pixi-layered-rig');
    assert.deepEqual(rigContract.requiredParts, [
      'head',
      'bangs',
      'bun',
      'face',
      'eyes',
      'mouth',
      'torso',
      'bow',
      'leftArm',
      'rightArm',
      'leftLeg',
      'rightLeg',
    ]);
  });

  test('declares controllable expression layers, presets, and behavior mappings', () => {
    const manifest = readJson(manifestPath);
    const rigContract = readJson(join(repoRoot, manifest.characterRig.contract));
    const expression = rigContract.expression;

    assert.deepEqual(expression.layers, [
      'face/base',
      'face/eyes',
      'face/mouth',
      'face/brows',
      'face/blush',
      'face/effects',
    ]);
    assert.equal(expression.defaultPreset, 'neutral');

    const presets = new Map(expression.presets.map((preset) => [preset.id, preset]));
    for (const id of [
      'neutral',
      'happy',
      'shy',
      'sleepy',
      'angry',
      'sad',
      'surprised',
      'blink',
      'talk_small',
      'talk_round',
      'talk_flat',
    ]) {
      assert.ok(presets.has(id), `missing expression preset ${id}`);
    }

    for (const preset of presets.values()) {
      assert.equal(typeof preset.label, 'string');
      assert.ok(preset.label.length > 0, `${preset.id} needs a label`);
      assert.ok(preset.parts.eyes, `${preset.id} needs eyes`);
      assert.ok(preset.parts.mouth, `${preset.id} needs mouth`);
      assert.ok(preset.parts.brows, `${preset.id} needs brows`);
    }

    assert.equal(expression.behaviorMap.pet.primary, 'happy');
    assert.equal(expression.behaviorMap.bath.primary, 'happy');
    assert.equal(expression.behaviorMap.sleep.primary, 'sleepy');
    assert.equal(expression.behaviorMap.whip.primary, 'sad');
    assert.deepEqual(expression.talkCycle, ['talk_small', 'talk_round', 'talk_flat']);
    assert.equal(expression.runtime.controlModule, 'src/shared/yoyo-expression-controls.js');
    assert.deepEqual(expression.runtime.currentSurfaces, ['speech-bubble-avatar']);
    assert.equal(expression.runtime.mainCanvasDynamicFace, false);
    assert.equal(expression.runtime.legacyAliases.heart, 'happy');
  });

  test('materializes V3 expression presets from the accepted reference rig', () => {
    const manifest = readJson(manifestPath);
    const rigContract = readJson(join(repoRoot, manifest.characterRig.contract));
    const expression = rigContract.expression;

    assert.equal(rigContract.source, 'assets-src/yoyo/v3/character-rig/yoyo-v3-reference-lock.png');
    assert.equal(expression.runtime.sourceRig, 'assets-src/yoyo/rig/live2d-yoyo-v5');
    assert.equal(expression.runtime.previewDir, 'assets-src/yoyo/v3/character-rig/expressions');
    assert.equal(expression.runtime.qaContactSheet, 'assets/yoyo/qa/v3/expression-presets-contact-sheet.png');
    assert.equal(
      statSync(join(repoRoot, rigContract.source)).size,
      statSync(join(repoRoot, 'assets-src/yoyo/reference/rig/yoyo-standing-clean2d-v3-alpha.png')).size,
      'reference lock should use the user-approved V3 alpha source',
    );

    for (const preset of expression.presets) {
      const expectedPath = join(repoRoot, expression.runtime.previewDir, `${preset.id}.png`);
      assert.ok(existsSync(expectedPath), `missing expression preview ${preset.id}`);
    }
    assert.ok(existsSync(join(repoRoot, expression.runtime.qaContactSheet)), 'missing expression contact sheet');
  });
});
