(function () {
  const asset = (name) => `../assets/yoyo/home/${name}.webp`;
  const actionTimelines = {
    feed: [
      { at: 0, state: 'idle', phase: 'notice', stagePhase: 'anticipate', pose: 'look-target', animation: 'feed_notice' },
      { at: 360, state: 'idle', phase: 'walk', stagePhase: 'enter', pose: 'step', animation: 'feed_walk_to_table' },
      { at: 1060, state: 'full', phase: 'inspect', stagePhase: 'inspect', pose: 'look-food', animation: 'feed_inspect_food' },
      { at: 1550, state: 'eating', phase: 'active', stagePhase: 'active', pose: 'eat-loop', animation: 'feed_eat_loop' },
      { at: 4250, state: 'done', phase: 'complete', stagePhase: 'complete', pose: 'happy', animation: 'feed_satisfied' },
      { at: 5050, state: 'done', phase: 'settle', stagePhase: 'settle', pose: 'idle', animation: 'feed_return_idle' },
    ],
    bath: [
      { at: 0, state: 'ready', phase: 'notice', stagePhase: 'anticipate', pose: 'look-target', animation: 'bath_notice' },
      { at: 260, state: 'ready', phase: 'walk', stagePhase: 'enter', pose: 'step', animation: 'bath_walk_to_sink' },
      { at: 960, state: 'bathing', phase: 'active', stagePhase: 'active', pose: 'wash-loop', animation: 'bath_wash_loop' },
      { at: 4300, state: 'done', phase: 'complete', stagePhase: 'complete', pose: 'fresh', animation: 'bath_sparkle' },
      { at: 5050, state: 'done', phase: 'settle', stagePhase: 'settle', pose: 'idle', animation: 'bath_return_idle' },
    ],
    sleep: [
      { at: 0, state: 'open', phase: 'notice', stagePhase: 'anticipate', pose: 'sleepy', animation: 'sleep_notice' },
      { at: 300, state: 'open', phase: 'walk', stagePhase: 'enter', pose: 'step-slow', animation: 'sleep_walk_to_bed' },
      { at: 1080, state: 'resting', phase: 'active', stagePhase: 'active', pose: 'sleep-loop', animation: 'sleep_curl_loop' },
      { at: 4300, state: 'done', phase: 'complete', stagePhase: 'complete', pose: 'dream', animation: 'sleep_dream' },
      { at: 5100, state: 'done', phase: 'settle', stagePhase: 'settle', pose: 'sleep-loop', animation: 'sleep_stay_tucked' },
    ],
    play: [
      { at: 0, state: 'ready', phase: 'notice', stagePhase: 'anticipate', pose: 'look-target', animation: 'play_notice' },
      { at: 260, state: 'ready', phase: 'walk', stagePhase: 'enter', pose: 'step', animation: 'play_walk_to_toys' },
      { at: 900, state: 'playing', phase: 'active', stagePhase: 'active', pose: 'play-loop', animation: 'play_active_loop' },
      { at: 4300, state: 'done', phase: 'complete', stagePhase: 'complete', pose: 'cheer', animation: 'play_cheer' },
      { at: 5050, state: 'done', phase: 'settle', stagePhase: 'settle', pose: 'idle', animation: 'play_return_idle' },
    ],
    pet: [
      { at: 0, state: 'ready', phase: 'notice', stagePhase: 'anticipate', pose: 'look-user', animation: 'pet_notice' },
      { at: 260, state: 'ready', phase: 'walk', stagePhase: 'enter', pose: 'step', animation: 'pet_walk_to_spot' },
      { at: 900, state: 'petting', phase: 'active', stagePhase: 'active', pose: 'happy-loop', animation: 'pet_happy_loop' },
      { at: 4300, state: 'done', phase: 'complete', stagePhase: 'complete', pose: 'heart', animation: 'pet_affection' },
      { at: 5050, state: 'done', phase: 'settle', stagePhase: 'settle', pose: 'idle', animation: 'pet_return_idle' },
    ],
    watchAnime: [
      { at: 0, state: 'ready', phase: 'notice', stagePhase: 'anticipate', pose: 'look-screen', animation: 'watch_anime_notice' },
      { at: 260, state: 'ready', phase: 'walk', stagePhase: 'enter', pose: 'sit-down', animation: 'watch_anime_sit_down' },
      { at: 900, state: 'watching', phase: 'active', stagePhase: 'active', pose: 'watch-loop', animation: 'watch_anime_watch_loop' },
      { at: 4300, state: 'done', phase: 'complete', stagePhase: 'complete', pose: 'delighted', animation: 'watch_anime_delighted' },
      { at: 5050, state: 'done', phase: 'settle', stagePhase: 'settle', pose: 'idle', animation: 'watch_anime_return_idle' },
    ],
    playSwitch: [
      { at: 0, state: 'ready', phase: 'notice', stagePhase: 'anticipate', pose: 'look-screen', animation: 'play_switch_notice' },
      { at: 260, state: 'ready', phase: 'walk', stagePhase: 'enter', pose: 'sit-down', animation: 'play_switch_sit_down' },
      { at: 900, state: 'gaming', phase: 'active', stagePhase: 'active', pose: 'game-loop', animation: 'play_switch_play_loop' },
      { at: 4300, state: 'done', phase: 'complete', stagePhase: 'complete', pose: 'victory', animation: 'play_switch_victory' },
      { at: 5050, state: 'done', phase: 'settle', stagePhase: 'settle', pose: 'idle', animation: 'play_switch_return_idle' },
    ],
    buildBlocks: [
      { at: 0, state: 'ready', phase: 'notice', stagePhase: 'anticipate', pose: 'look-blocks', animation: 'build_blocks_notice' },
      { at: 260, state: 'ready', phase: 'walk', stagePhase: 'enter', pose: 'kneel-down', animation: 'build_blocks_kneel_down' },
      { at: 900, state: 'building', phase: 'active', stagePhase: 'active', pose: 'build-loop', animation: 'build_blocks_build_loop' },
      { at: 4300, state: 'done', phase: 'complete', stagePhase: 'complete', pose: 'proud', animation: 'build_blocks_proud' },
      { at: 5050, state: 'done', phase: 'settle', stagePhase: 'settle', pose: 'idle', animation: 'build_blocks_return_idle' },
    ],
    study: [
      { at: 0, state: 'ready', phase: 'notice', stagePhase: 'anticipate', pose: 'look-book', animation: 'study_notice' },
      { at: 260, state: 'ready', phase: 'walk', stagePhase: 'enter', pose: 'step', animation: 'study_walk_to_desk' },
      { at: 900, state: 'studying', phase: 'active', stagePhase: 'active', pose: 'focus-loop', animation: 'study_focus_loop' },
      { at: 4300, state: 'done', phase: 'complete', stagePhase: 'complete', pose: 'star', animation: 'study_star' },
      { at: 5050, state: 'done', phase: 'settle', stagePhase: 'settle', pose: 'idle', animation: 'study_return_idle' },
    ],
  };
  const requiredAnimations = Object.fromEntries(
    Object.entries(actionTimelines).map(([action, timeline]) => [
      action,
      timeline.map((step) => step.animation),
    ]),
  );

  window.YOYO_HOME_SCENE = {
    roomLayout: {
      baseAsset: asset('room-v3-day-safe'),
      artMode: 'saved-compact-room',
      designSize: { width: 1272, height: 720 },
      slots: {
        feed: { left: '14.76%', bottom: '9%', width: '210px', zIndex: 7, semantic: 'meal-table' },
        bath: { left: '75%', bottom: '8%', width: '230px', zIndex: 7, semantic: 'wash-stand' },
        sleep: { left: '66.98%', bottom: '19%', width: '340px', zIndex: 7, semantic: 'child-bed' },
        play: { left: '50%', bottom: '22%', width: '230px', zIndex: 5, semantic: 'toy-shelf' },
        pet: { left: '34.91%', bottom: '18%', width: '210px', zIndex: 6, semantic: 'companionship-spot' },
        watchAnime: { left: '60.19%', bottom: '34%', width: '235px', zIndex: 4, semantic: 'media-screen' },
        playSwitch: { left: '60.19%', bottom: '24%', width: '235px', zIndex: 5, semantic: 'game-console' },
        buildBlocks: { left: '51.70%', bottom: '8%', width: '200px', zIndex: 6, semantic: 'block-play' },
        study: { left: '59.34%', bottom: '16%', width: '285px', zIndex: 4, semantic: 'study-desk' },
      },
    },
    expandedHouse: {
      enabled: false,
      worldWidth: 1272,
      viewportWidth: 1272,
      defaultCamera: 'living',
      actionCamera: {
        feed: 'kitchen',
        pet: 'living',
        play: 'play',
        buildBlocks: 'play',
        study: 'play',
        watchAnime: 'play',
        playSwitch: 'play',
        sleep: 'sleep',
        bath: 'sleep',
      },
      cameraStops: {
        kitchen: { x: 0, label: '厨房 / 餐厅' },
        living: { x: 424, label: '客厅 / 陪伴' },
        play: { x: 966, label: '玩耍 / 学习' },
        sleep: { x: 1272, label: '睡觉小屋' },
      },
    },
    petPlacements: {
      default: { left: '35.66%', bottom: '100px', scale: 0.76 },
      feed: { left: '31.20%', bottom: '98px', scale: 0.60 },
      bath: { left: '80%', bottom: '142px', scale: 0.60 },
      sleep: { left: '74.62%', bottom: '196px', scale: 0.62 },
      play: { left: '54.25%', bottom: '192px', scale: 0.64 },
      pet: { left: '37.36%', bottom: '164px', scale: 0.68 },
      watchAnime: { left: '63.58%', bottom: '172px', scale: 0.62 },
      playSwitch: { left: '63.58%', bottom: '172px', scale: 0.62 },
      buildBlocks: { left: '55.09%', bottom: '160px', scale: 0.64 },
      study: { left: '62.74%', bottom: '175px', scale: 0.60 },
    },
    actionMotion: {
      feed: {
        petTravel: {
          from: 'default',
          to: 'feed',
          durationMs: 1040,
          easing: 'cubic-bezier(0.18, 0.84, 0.24, 1)',
        },
      },
    },
    sceneRigs: {},
    specialPoses: {},
    actionComposites: {},
    actionRooms: {},
    homeCharacter: {
      mode: 'v7-cutout',
      cutout: asset('yoyo-home-v7-room-palette'),
      fallbackMode: 'sprite-canvas',
    },
    actionRuntime: {
      targetDriver: 'spine-pixi-v8',
      fallbackDriver: 'css-v7-cutout',
      stateAttribute: 'data-action-animation',
      phaseAttribute: 'data-action-phase',
      motionAttribute: 'data-motion-phase',
      assetStatus: 'desktop-rig-v1-local',
      requiredAnimations,
      desktopRig: {
        manifest: '../assets/yoyo/desktop-rig/v1/manifest.json',
        source: 'assets/yoyo/desktop-rig/v1',
        driver: 'pixi-layered-rig',
        actions: Object.keys(actionTimelines),
      },
    },
    interactionSystem: {
      zones: {
        default: { placement: 'default', label: '客厅中央', camera: 'living' },
        feed: { placement: 'feed', slot: 'feed', label: '餐桌', camera: 'kitchen' },
        bath: { placement: 'bath', slot: 'bath', label: '洗漱区', camera: 'sleep' },
        sleep: { placement: 'sleep', slot: 'sleep', label: '小床', camera: 'sleep' },
        play: { placement: 'play', slot: 'play', label: '玩具区', camera: 'play' },
        pet: { placement: 'pet', slot: 'pet', label: '陪伴位', camera: 'living' },
        watchAnime: { placement: 'watchAnime', slot: 'watchAnime', label: '电视区', camera: 'play' },
        playSwitch: { placement: 'playSwitch', slot: 'playSwitch', label: '游戏区', camera: 'play' },
        buildBlocks: { placement: 'buildBlocks', slot: 'buildBlocks', label: '积木区', camera: 'play' },
        study: { placement: 'study', slot: 'study', label: '学习区', camera: 'play' },
      },
      tasks: {
        feed: {
          zone: 'feed',
          objectId: 'foodBowl',
          yoyoState: 'eating',
          mode: 'native-room-zone',
          phases: [
            { at: 0, state: 'full', stagePhase: 'approach' },
            { at: 600, state: 'eating', stagePhase: 'active' },
            { at: 4600, state: 'done', stagePhase: 'satisfied' },
          ],
          timeline: actionTimelines.feed,
          resetDelay: 5200,
        },
        bath: {
          zone: 'bath',
          objectId: 'bathTub',
          yoyoState: 'fanCooling',
          mode: 'native-room-zone',
          phases: [
            { at: 0, state: 'ready', stagePhase: 'approach' },
            { at: 600, state: 'bathing', stagePhase: 'active' },
            { at: 4600, state: 'done', stagePhase: 'satisfied' },
          ],
          timeline: actionTimelines.bath,
          resetDelay: 5200,
        },
        sleep: {
          zone: 'sleep',
          objectId: 'sleepBed',
          yoyoState: 'sleeping',
          mode: 'native-room-zone',
          phases: [
            { at: 0, state: 'open', stagePhase: 'approach' },
            { at: 600, state: 'resting', stagePhase: 'active' },
            { at: 4600, state: 'done', stagePhase: 'satisfied' },
          ],
          timeline: actionTimelines.sleep,
          resetDelay: 5200,
        },
        play: {
          zone: 'play',
          objectId: 'toyBox',
          yoyoState: 'jumping',
          mode: 'native-room-zone',
          phases: [
            { at: 0, state: 'ready', stagePhase: 'approach' },
            { at: 600, state: 'playing', stagePhase: 'active' },
            { at: 4600, state: 'done', stagePhase: 'satisfied' },
          ],
          timeline: actionTimelines.play,
          resetDelay: 5200,
        },
        pet: {
          zone: 'pet',
          objectId: 'heartSpot',
          yoyoState: 'petting',
          mode: 'native-room-zone',
          phases: [
            { at: 0, state: 'ready', stagePhase: 'approach' },
            { at: 600, state: 'petting', stagePhase: 'active' },
            { at: 4600, state: 'done', stagePhase: 'satisfied' },
          ],
          timeline: actionTimelines.pet,
          resetDelay: 5200,
        },
        watchAnime: {
          zone: 'watchAnime',
          objectId: 'mediaCorner',
          yoyoState: 'watchTV',
          mode: 'native-room-zone',
          phases: [
            { at: 0, state: 'ready', stagePhase: 'approach' },
            { at: 600, state: 'watching', stagePhase: 'active' },
            { at: 4600, state: 'done', stagePhase: 'satisfied' },
          ],
          timeline: actionTimelines.watchAnime,
          resetDelay: 5200,
        },
        playSwitch: {
          zone: 'playSwitch',
          objectId: 'switchCorner',
          yoyoState: 'review',
          mode: 'native-room-zone',
          phases: [
            { at: 0, state: 'ready', stagePhase: 'approach' },
            { at: 600, state: 'gaming', stagePhase: 'active' },
            { at: 4600, state: 'done', stagePhase: 'satisfied' },
          ],
          timeline: actionTimelines.playSwitch,
          resetDelay: 5200,
        },
        buildBlocks: {
          zone: 'buildBlocks',
          objectId: 'blocksCorner',
          yoyoState: 'review',
          mode: 'native-room-zone',
          phases: [
            { at: 0, state: 'ready', stagePhase: 'approach' },
            { at: 600, state: 'building', stagePhase: 'active' },
            { at: 4600, state: 'done', stagePhase: 'satisfied' },
          ],
          timeline: actionTimelines.buildBlocks,
          resetDelay: 5200,
        },
        study: {
          zone: 'study',
          objectId: 'studyCorner',
          yoyoState: 'review',
          mode: 'native-room-zone',
          phases: [
            { at: 0, state: 'ready', stagePhase: 'approach' },
            { at: 600, state: 'studying', stagePhase: 'active' },
            { at: 4600, state: 'done', stagePhase: 'satisfied' },
          ],
          timeline: actionTimelines.study,
          resetDelay: 5200,
        },
      },
    },
    decor: [
      {
        id: 'kitchenWallTiles',
        className: 'home-fixture kitchen-wall-tiles',
        slot: { left: '0%', top: '12%', width: '25%', zIndex: 1 },
        label: '厨房瓷砖',
      },
      {
        id: 'kitchenCounter',
        className: 'home-fixture kitchen-counter',
        slot: { left: '10%', bottom: '40%', width: '310px', zIndex: 4 },
        label: '厨房台面',
      },
      {
        id: 'kitchenRange',
        className: 'home-fixture kitchen-range',
        slot: { left: '18.5%', bottom: '40%', width: '94px', zIndex: 5 },
        label: '炉灶',
      },
      {
        id: 'kitchenFridge',
        className: 'home-fixture kitchen-fridge',
        slot: { left: '2%', bottom: '36%', width: '100px', zIndex: 4 },
        label: '冰箱',
      },
      {
        id: 'kitchenUpperCabinet',
        className: 'home-fixture kitchen-upper-cabinet',
        slot: { left: '9%', top: '17%', width: '250px', zIndex: 4 },
        label: '厨房吊柜',
      },
      {
        id: 'livingWindow',
        className: 'home-fixture living-window-fixture',
        slot: { left: '28%', top: '8%', width: '330px', zIndex: 2 },
        label: '客厅窗户',
      },
      {
        id: 'livingSofa',
        className: 'home-fixture living-sofa',
        slot: { left: '28%', bottom: '14%', width: '330px', zIndex: 4 },
        label: '客厅沙发',
      },
      {
        id: 'livingCoffeeTable',
        className: 'home-fixture living-coffee-table',
        slot: { left: '36%', bottom: '9%', width: '168px', zIndex: 5 },
        label: '客厅茶几',
      },
      {
        id: 'livingFloorLamp',
        className: 'home-fixture living-floor-lamp',
        slot: { left: '43.5%', bottom: '15%', width: '72px', zIndex: 4 },
        label: '落地灯',
      },
      {
        id: 'playFloorMat',
        className: 'home-fixture play-floor-mat',
        slot: { left: '48.5%', bottom: '4%', width: '520px', zIndex: 1 },
        label: '玩耍地毯',
      },
      {
        id: 'sleepCurtain',
        className: 'home-fixture sleep-curtain',
        slot: { left: '74%', top: '5%', width: '300px', zIndex: 2 },
        label: '睡觉区窗帘',
      },
      {
        id: 'bedsideDrawer',
        className: 'home-fixture bedside-drawer',
        slot: { left: '94%', bottom: '19%', width: '92px', zIndex: 5 },
        label: '床边柜',
      },
      {
        id: 'sleepRug',
        className: 'home-fixture sleep-rug',
        slot: { left: '77%', bottom: '4%', width: '440px', zIndex: 1 },
        label: '睡觉区地毯',
      },
      {
        id: 'wallAirConditioner',
        className: 'home-fixture wall-air-conditioner',
        slot: { left: '74.5%', top: '7%', width: '128px', zIndex: 3 },
        label: '空调',
      },
      {
        id: 'wallClock',
        className: 'home-fixture wall-clock',
        slot: { left: '82%', top: '13%', width: '42px', zIndex: 5 },
        label: '墙钟',
      },
      {
        id: 'lightSwitch',
        className: 'home-fixture light-switch',
        slot: { left: '79%', top: '39%', width: '18px', zIndex: 3 },
        label: '开关',
      },
      {
        id: 'floorOutlet',
        className: 'home-fixture floor-outlet',
        slot: { left: '84%', bottom: '48%', width: '22px', zIndex: 3 },
        label: '插座',
      },
      {
        id: 'houseSlippers',
        className: 'home-fixture house-slippers',
        slot: { left: '84%', bottom: '8%', width: '58px', zIndex: 6 },
        label: '拖鞋',
      },
      {
        id: 'softStorageBasket',
        className: 'home-fixture soft-storage-basket',
        slot: { left: '53%', bottom: '10%', width: '48px', zIndex: 6 },
        label: '收纳篮',
      },
    ],
    objects: [
      {
        id: 'foodBowl',
        action: 'feed',
        slot: 'feed',
        className: 'food-bowl-object',
        initialState: 'idle',
        label: '小餐桌',
        layers: [
          { id: 'back', className: 'food-bowl-back', src: asset('prop-v3-meal-table') },
        ],
      },
      {
        id: 'bathTub',
        action: 'bath',
        slot: 'bath',
        className: 'bath-tub-object',
        initialState: 'idle',
        label: '洗漱区',
        layers: [
          { id: 'back', className: 'bath-tub-back', src: asset('prop-v3-wash-stand') },
        ],
      },
      {
        id: 'sleepBed',
        action: 'sleep',
        slot: 'sleep',
        className: 'sleep-bed-object',
        initialState: 'idle',
        label: 'Yoyo的小床',
        layers: [
          { id: 'back', className: 'sleep-bed-back', src: asset('prop-v3-bed') },
        ],
      },
      {
        id: 'toyBox',
        action: 'play',
        slot: 'play',
        className: 'toy-box-object',
        initialState: 'idle',
        label: '玩具架',
        layers: [
          { id: 'back', className: 'toy-box-back', src: asset('prop-v3-toy-shelf') },
        ],
      },
      {
        id: 'heartSpot',
        action: 'pet',
        slot: 'pet',
        className: 'heart-spot-object',
        initialState: 'idle',
        label: '陪伴位置',
        layers: [
          { id: 'back', className: 'heart-spot-back', src: asset('prop-v3-comfort-cushion') },
        ],
      },
      {
        id: 'mediaCorner',
        action: 'watchAnime',
        slot: 'watchAnime',
        className: 'media-corner-object',
        initialState: 'idle',
        label: '动画电视',
        layers: [
          { id: 'back', className: 'media-corner-back', src: asset('prop-v3-media-screen') },
        ],
      },
      {
        id: 'switchCorner',
        action: 'playSwitch',
        slot: 'playSwitch',
        className: 'switch-corner-object',
        initialState: 'idle',
        label: 'Switch游戏区',
        layers: [
          { id: 'back', className: 'switch-corner-back', src: asset('prop-v3-game-console') },
        ],
      },
      {
        id: 'blocksCorner',
        action: 'buildBlocks',
        slot: 'buildBlocks',
        className: 'blocks-corner-object',
        initialState: 'idle',
        label: '积木区',
        layers: [
          { id: 'back', className: 'blocks-corner-back', src: asset('prop-v3-blocks') },
        ],
      },
      {
        id: 'studyCorner',
        action: 'study',
        slot: 'study',
        className: 'study-corner-object',
        initialState: 'idle',
        label: '学习书桌',
        layers: [
          { id: 'back', className: 'study-corner-back', src: asset('prop-v3-study-desk') },
        ],
      },
    ],
    interactions: {
      feed: {
        objectId: 'foodBowl',
        mode: 'native-room-zone',
        phases: [
          { at: 0, state: 'full', stagePhase: 'approach' },
          { at: 600, state: 'eating', stagePhase: 'active' },
          { at: 4600, state: 'done', stagePhase: 'satisfied' },
        ],
        timeline: actionTimelines.feed,
        resetDelay: 5200,
      },
      bath: {
        objectId: 'bathTub',
        mode: 'native-room-zone',
        phases: [
          { at: 0, state: 'ready', stagePhase: 'approach' },
          { at: 600, state: 'bathing', stagePhase: 'active' },
          { at: 4600, state: 'done', stagePhase: 'satisfied' },
        ],
        timeline: actionTimelines.bath,
        resetDelay: 5200,
      },
      sleep: {
        objectId: 'sleepBed',
        mode: 'native-room-zone',
        phases: [
          { at: 0, state: 'open', stagePhase: 'approach' },
          { at: 600, state: 'resting', stagePhase: 'active' },
          { at: 4600, state: 'done', stagePhase: 'satisfied' },
        ],
        timeline: actionTimelines.sleep,
        resetDelay: 5200,
      },
      play: {
        objectId: 'toyBox',
        mode: 'native-room-zone',
        phases: [
          { at: 0, state: 'ready', stagePhase: 'approach' },
          { at: 600, state: 'playing', stagePhase: 'active' },
          { at: 4600, state: 'done', stagePhase: 'satisfied' },
        ],
        timeline: actionTimelines.play,
        resetDelay: 5200,
      },
      pet: {
        objectId: 'heartSpot',
        mode: 'native-room-zone',
        phases: [
          { at: 0, state: 'ready', stagePhase: 'approach' },
          { at: 600, state: 'petting', stagePhase: 'active' },
          { at: 4600, state: 'done', stagePhase: 'satisfied' },
        ],
        timeline: actionTimelines.pet,
        resetDelay: 5200,
      },
      watchAnime: {
        objectId: 'mediaCorner',
        mode: 'native-room-zone',
        phases: [
          { at: 0, state: 'ready', stagePhase: 'approach' },
          { at: 600, state: 'watching', stagePhase: 'active' },
          { at: 4600, state: 'done', stagePhase: 'satisfied' },
        ],
        timeline: actionTimelines.watchAnime,
        resetDelay: 5200,
      },
      playSwitch: {
        objectId: 'switchCorner',
        mode: 'native-room-zone',
        phases: [
          { at: 0, state: 'ready', stagePhase: 'approach' },
          { at: 600, state: 'gaming', stagePhase: 'active' },
          { at: 4600, state: 'done', stagePhase: 'satisfied' },
        ],
        timeline: actionTimelines.playSwitch,
        resetDelay: 5200,
      },
      buildBlocks: {
        objectId: 'blocksCorner',
        mode: 'native-room-zone',
        phases: [
          { at: 0, state: 'ready', stagePhase: 'approach' },
          { at: 600, state: 'building', stagePhase: 'active' },
          { at: 4600, state: 'done', stagePhase: 'satisfied' },
        ],
        timeline: actionTimelines.buildBlocks,
        resetDelay: 5200,
      },
      study: {
        objectId: 'studyCorner',
        mode: 'native-room-zone',
        phases: [
          { at: 0, state: 'ready', stagePhase: 'approach' },
          { at: 600, state: 'studying', stagePhase: 'active' },
          { at: 4600, state: 'done', stagePhase: 'satisfied' },
        ],
        timeline: actionTimelines.study,
        resetDelay: 5200,
      },
    },
  };
}());
