(function () {
  const asset = (name) => `../assets/yoyo/home/${name}.webp`;

  window.YOYO_HOME_SCENE = {
    roomLayout: {
      baseAsset: asset('room-v3-day'),
      artMode: 'saved-compact-room',
      designSize: { width: 2160, height: 720 },
      slots: {
        feed: { left: '8.5%', bottom: '9%', width: '210px', zIndex: 7, semantic: 'meal-table' },
        bath: { left: '82%', bottom: '8%', width: '250px', zIndex: 7, semantic: 'wash-stand' },
        sleep: { left: '76%', bottom: '20%', width: '360px', zIndex: 7, semantic: 'child-bed' },
        play: { left: '50%', bottom: '22%', width: '230px', zIndex: 5, semantic: 'toy-shelf' },
        pet: { left: '32%', bottom: '18%', width: '210px', zIndex: 6, semantic: 'companionship-spot' },
        watchAnime: { left: '62%', bottom: '34%', width: '235px', zIndex: 4, semantic: 'media-screen' },
        playSwitch: { left: '62%', bottom: '24%', width: '235px', zIndex: 5, semantic: 'game-console' },
        buildBlocks: { left: '52%', bottom: '8%', width: '200px', zIndex: 6, semantic: 'block-play' },
        study: { left: '61%', bottom: '16%', width: '285px', zIndex: 4, semantic: 'study-desk' },
      },
    },
    expandedHouse: {
      enabled: true,
      worldWidth: 2160,
      viewportWidth: 1080,
      defaultCamera: 'living',
      actionCamera: {
        feed: 'kitchen',
        pet: 'living',
        play: 'play',
        buildBlocks: 'play',
        study: 'play',
        watchAnime: 'play',
        playSwitch: 'play',
        sleep: 'sleep',
        bath: 'sleep',
      },
      cameraStops: {
        kitchen: { x: 0, label: '厨房 / 餐厅' },
        living: { x: 360, label: '客厅 / 陪伴' },
        play: { x: 820, label: '玩耍 / 学习' },
        sleep: { x: 1080, label: '睡觉小屋' },
      },
    },
    petPlacements: {
      default: { left: '33%', bottom: '100px', scale: 0.72 },
      feed: { left: '24%', bottom: '118px', scale: 0.52 },
      bath: { left: '91%', bottom: '165px', scale: 0.54 },
      sleep: { left: '83%', bottom: '222px', scale: 0.62 },
      play: { left: '55%', bottom: '192px', scale: 0.58 },
      pet: { left: '35%', bottom: '164px', scale: 0.64 },
      watchAnime: { left: '66%', bottom: '172px', scale: 0.58 },
      playSwitch: { left: '66%', bottom: '172px', scale: 0.58 },
      buildBlocks: { left: '56%', bottom: '160px', scale: 0.58 },
      study: { left: '65%', bottom: '175px', scale: 0.56 },
    },
    sceneRigs: {},
    specialPoses: {},
    actionComposites: {
      feed: {
        objectId: 'foodBowl',
        semantic: 'meal-table-feed',
        src: asset('composite-v3-feed-yoyo'),
        slot: { left: '6.5%', bottom: '8%', width: '360px', zIndex: 7 },
      },
      sleep: {
        objectId: 'sleepBed',
        semantic: 'child-bed-sleep',
        src: asset('composite-v3-sleep-yoyo'),
        slot: { left: '72%', bottom: '16%', width: '440px', zIndex: 7 },
      },
      bath: {
        objectId: 'bathTub',
        semantic: 'wash-stand-hands',
        src: asset('composite-v3-bath-yoyo'),
        slot: { left: '73%', bottom: '9%', width: '390px', zIndex: 7 },
      },
      play: {
        objectId: 'toyBox',
        semantic: 'toy-shelf-play',
        src: asset('composite-v3-play-yoyo'),
        slot: { left: '48%', bottom: '14%', width: '390px', zIndex: 7 },
      },
      pet: {
        objectId: 'heartSpot',
        semantic: 'cushion-head-pat',
        src: asset('composite-v3-comfort-yoyo'),
        slot: { left: '26%', bottom: '15%', width: '360px', zIndex: 7 },
      },
    },
    actionRooms: {},
    interactionSystem: {
      zones: {
        default: { placement: 'default', label: '客厅中央', camera: 'living' },
        feed: { placement: 'feed', slot: 'feed', label: '餐桌', camera: 'kitchen' },
        bath: { placement: 'bath', slot: 'bath', label: '洗漱区', camera: 'sleep' },
        sleep: { placement: 'sleep', slot: 'sleep', label: '小床', camera: 'sleep' },
        play: { placement: 'play', slot: 'play', label: '玩具区', camera: 'play' },
        pet: { placement: 'pet', slot: 'pet', label: '陪伴位', camera: 'living' },
        watchAnime: { placement: 'watchAnime', slot: 'watchAnime', label: '电视区', camera: 'play' },
        playSwitch: { placement: 'playSwitch', slot: 'playSwitch', label: '游戏区', camera: 'play' },
        buildBlocks: { placement: 'buildBlocks', slot: 'buildBlocks', label: '积木区', camera: 'play' },
        study: { placement: 'study', slot: 'study', label: '学习区', camera: 'play' },
      },
      tasks: {
        feed: {
          zone: 'feed',
          objectId: 'foodBowl',
          yoyoState: 'eating',
          mode: 'localized-composite',
          phases: [
            { at: 0, state: 'full', stagePhase: 'approach' },
            { at: 600, state: 'eating', stagePhase: 'active' },
            { at: 4600, state: 'done', stagePhase: 'satisfied' },
          ],
          resetDelay: 5200,
        },
        bath: {
          zone: 'bath',
          objectId: 'bathTub',
          yoyoState: 'fanCooling',
          mode: 'localized-composite',
          phases: [
            { at: 0, state: 'ready', stagePhase: 'approach' },
            { at: 600, state: 'bathing', stagePhase: 'active' },
            { at: 4600, state: 'done', stagePhase: 'satisfied' },
          ],
          resetDelay: 5200,
        },
        sleep: {
          zone: 'sleep',
          objectId: 'sleepBed',
          yoyoState: 'sleeping',
          mode: 'localized-composite',
          phases: [
            { at: 0, state: 'open', stagePhase: 'approach' },
            { at: 600, state: 'resting', stagePhase: 'active' },
            { at: 4600, state: 'done', stagePhase: 'satisfied' },
          ],
          resetDelay: 5200,
        },
        play: {
          zone: 'play',
          objectId: 'toyBox',
          yoyoState: 'jumping',
          mode: 'localized-composite',
          phases: [
            { at: 0, state: 'ready', stagePhase: 'approach' },
            { at: 600, state: 'playing', stagePhase: 'active' },
            { at: 4600, state: 'done', stagePhase: 'satisfied' },
          ],
          resetDelay: 5200,
        },
        pet: {
          zone: 'pet',
          objectId: 'heartSpot',
          yoyoState: 'petting',
          mode: 'localized-composite',
          phases: [
            { at: 0, state: 'ready', stagePhase: 'approach' },
            { at: 600, state: 'petting', stagePhase: 'active' },
            { at: 4600, state: 'done', stagePhase: 'satisfied' },
          ],
          resetDelay: 5200,
        },
        watchAnime: {
          zone: 'watchAnime',
          objectId: 'mediaCorner',
          yoyoState: 'watchTV',
          mode: 'layered-prop',
          phases: [
            { at: 0, state: 'ready', stagePhase: 'approach' },
            { at: 600, state: 'watching', stagePhase: 'active' },
            { at: 4600, state: 'done', stagePhase: 'satisfied' },
          ],
          resetDelay: 5200,
        },
        playSwitch: {
          zone: 'playSwitch',
          objectId: 'switchCorner',
          yoyoState: 'review',
          mode: 'layered-prop',
          phases: [
            { at: 0, state: 'ready', stagePhase: 'approach' },
            { at: 600, state: 'gaming', stagePhase: 'active' },
            { at: 4600, state: 'done', stagePhase: 'satisfied' },
          ],
          resetDelay: 5200,
        },
        buildBlocks: {
          zone: 'buildBlocks',
          objectId: 'blocksCorner',
          yoyoState: 'review',
          mode: 'layered-prop',
          phases: [
            { at: 0, state: 'ready', stagePhase: 'approach' },
            { at: 600, state: 'building', stagePhase: 'active' },
            { at: 4600, state: 'done', stagePhase: 'satisfied' },
          ],
          resetDelay: 5200,
        },
        study: {
          zone: 'study',
          objectId: 'studyCorner',
          yoyoState: 'review',
          mode: 'layered-prop',
          phases: [
            { at: 0, state: 'ready', stagePhase: 'approach' },
            { at: 600, state: 'studying', stagePhase: 'active' },
            { at: 4600, state: 'done', stagePhase: 'satisfied' },
          ],
          resetDelay: 5200,
        },
      },
    },
    decor: [
      {
        id: 'wallSoftFurnishing',
        src: asset('decor-wall-soft-furnishing'),
        slot: { left: '61%', bottom: '16%', width: '285px', zIndex: 4 },
        label: '墙边软装',
      },
      {
        id: 'tvGameToys',
        src: asset('decor-tv-game-toys'),
        slot: { left: '62%', bottom: '34%', width: '235px', zIndex: 4 },
        label: '电视游戏玩具区',
      },
      {
        id: 'kitchenWallTiles',
        className: 'home-fixture kitchen-wall-tiles',
        slot: { left: '0%', top: '12%', width: '25%', zIndex: 1 },
        label: '厨房瓷砖',
      },
      {
        id: 'kitchenCounter',
        className: 'home-fixture kitchen-counter',
        slot: { left: '10%', bottom: '40%', width: '310px', zIndex: 4 },
        label: '厨房台面',
      },
      {
        id: 'kitchenRange',
        className: 'home-fixture kitchen-range',
        slot: { left: '18.5%', bottom: '40%', width: '94px', zIndex: 5 },
        label: '炉灶',
      },
      {
        id: 'kitchenFridge',
        className: 'home-fixture kitchen-fridge',
        slot: { left: '2%', bottom: '36%', width: '100px', zIndex: 4 },
        label: '冰箱',
      },
      {
        id: 'kitchenUpperCabinet',
        className: 'home-fixture kitchen-upper-cabinet',
        slot: { left: '9%', top: '17%', width: '250px', zIndex: 4 },
        label: '厨房吊柜',
      },
      {
        id: 'livingWindow',
        className: 'home-fixture living-window-fixture',
        slot: { left: '28%', top: '8%', width: '330px', zIndex: 2 },
        label: '客厅窗户',
      },
      {
        id: 'livingSofa',
        className: 'home-fixture living-sofa',
        slot: { left: '28%', bottom: '14%', width: '330px', zIndex: 4 },
        label: '客厅沙发',
      },
      {
        id: 'livingCoffeeTable',
        className: 'home-fixture living-coffee-table',
        slot: { left: '36%', bottom: '9%', width: '168px', zIndex: 5 },
        label: '客厅茶几',
      },
      {
        id: 'livingFloorLamp',
        className: 'home-fixture living-floor-lamp',
        slot: { left: '43.5%', bottom: '15%', width: '72px', zIndex: 4 },
        label: '落地灯',
      },
      {
        id: 'playFloorMat',
        className: 'home-fixture play-floor-mat',
        slot: { left: '48.5%', bottom: '4%', width: '520px', zIndex: 1 },
        label: '玩耍地毯',
      },
      {
        id: 'sleepCurtain',
        className: 'home-fixture sleep-curtain',
        slot: { left: '74%', top: '5%', width: '300px', zIndex: 2 },
        label: '睡觉区窗帘',
      },
      {
        id: 'bedsideDrawer',
        className: 'home-fixture bedside-drawer',
        slot: { left: '94%', bottom: '19%', width: '92px', zIndex: 5 },
        label: '床边柜',
      },
      {
        id: 'sleepRug',
        className: 'home-fixture sleep-rug',
        slot: { left: '77%', bottom: '4%', width: '440px', zIndex: 1 },
        label: '睡觉区地毯',
      },
      {
        id: 'wallAirConditioner',
        className: 'home-fixture wall-air-conditioner',
        slot: { left: '74.5%', top: '7%', width: '128px', zIndex: 3 },
        label: '空调',
      },
      {
        id: 'wallClock',
        className: 'home-fixture wall-clock',
        slot: { left: '82%', top: '13%', width: '42px', zIndex: 5 },
        label: '墙钟',
      },
      {
        id: 'lightSwitch',
        className: 'home-fixture light-switch',
        slot: { left: '79%', top: '39%', width: '18px', zIndex: 3 },
        label: '开关',
      },
      {
        id: 'floorOutlet',
        className: 'home-fixture floor-outlet',
        slot: { left: '84%', bottom: '48%', width: '22px', zIndex: 3 },
        label: '插座',
      },
      {
        id: 'houseSlippers',
        className: 'home-fixture house-slippers',
        slot: { left: '84%', bottom: '8%', width: '58px', zIndex: 6 },
        label: '拖鞋',
      },
      {
        id: 'softStorageBasket',
        className: 'home-fixture soft-storage-basket',
        slot: { left: '53%', bottom: '10%', width: '48px', zIndex: 6 },
        label: '收纳篮',
      },
    ],
    objects: [
      {
        id: 'foodBowl',
        action: 'feed',
        slot: 'feed',
        className: 'food-bowl-object',
        initialState: 'idle',
        label: '小餐桌',
        layers: [
          { id: 'back', className: 'food-bowl-back', src: asset('prop-food-back') },
          { id: 'mealFull', className: 'food-bowl-meal-full', src: asset('prop-food-meal-full') },
          { id: 'mealLow', className: 'food-bowl-meal-low', src: asset('prop-food-meal-low') },
          { id: 'front', className: 'food-bowl-front', src: asset('prop-food-front') },
        ],
      },
      {
        id: 'bathTub',
        action: 'bath',
        slot: 'bath',
        className: 'bath-tub-object',
        initialState: 'idle',
        label: '洗漱区',
        layers: [
          { id: 'back', className: 'bath-tub-back', src: asset('prop-bath-back') },
          { id: 'water', className: 'bath-tub-water', src: asset('prop-bath-water') },
          { id: 'bubbles', className: 'bath-tub-bubbles', src: asset('prop-bath-bubbles') },
          { id: 'front', className: 'bath-tub-front', src: asset('prop-bath-front') },
        ],
      },
      {
        id: 'sleepBed',
        action: 'sleep',
        slot: 'sleep',
        className: 'sleep-bed-object',
        initialState: 'idle',
        label: 'Yoyo的小床',
        layers: [
          { id: 'back', className: 'sleep-bed-back', src: asset('prop-bed-clean') },
          { id: 'blanket', className: 'sleep-bed-blanket', src: asset('prop-bed-blanket') },
          { id: 'front', className: 'sleep-bed-front', src: asset('prop-bed-front') },
        ],
      },
      {
        id: 'toyBox',
        action: 'play',
        slot: 'play',
        className: 'toy-box-object',
        initialState: 'idle',
        label: '玩具架',
        layers: [
          { id: 'back', className: 'toy-box-back', src: asset('prop-toy-back') },
          { id: 'toys', className: 'toy-box-toys', src: asset('prop-toy-burst') },
          { id: 'front', className: 'toy-box-front', src: asset('prop-toy-front') },
        ],
      },
      {
        id: 'heartSpot',
        action: 'pet',
        slot: 'pet',
        className: 'heart-spot-object',
        initialState: 'idle',
        label: '陪伴位置',
        layers: [
          { id: 'back', className: 'heart-spot-back', src: asset('prop-heart-back') },
          { id: 'pulse', className: 'heart-spot-pulse', src: asset('prop-heart-pulse') },
          { id: 'front', className: 'heart-spot-front', src: asset('prop-heart-front') },
        ],
      },
      {
        id: 'mediaCorner',
        action: 'watchAnime',
        slot: 'watchAnime',
        className: 'media-corner-object',
        initialState: 'idle',
        label: '动画电视',
        layers: [
          { id: 'back', className: 'media-corner-back', src: asset('decor-tv-game-toys') },
          { id: 'front', className: 'media-corner-front', src: asset('decor-tv-game-toys') },
        ],
      },
      {
        id: 'switchCorner',
        action: 'playSwitch',
        slot: 'playSwitch',
        className: 'switch-corner-object',
        initialState: 'idle',
        label: 'Switch游戏区',
        layers: [
          { id: 'back', className: 'switch-corner-back', src: asset('decor-tv-game-toys') },
          { id: 'front', className: 'switch-corner-front', src: asset('decor-tv-game-toys') },
        ],
      },
      {
        id: 'blocksCorner',
        action: 'buildBlocks',
        slot: 'buildBlocks',
        className: 'blocks-corner-object',
        initialState: 'idle',
        label: '积木区',
        layers: [
          { id: 'back', className: 'blocks-corner-back', src: asset('prop-toy-back') },
          { id: 'blocks', className: 'blocks-corner-blocks', src: asset('prop-toy-burst') },
          { id: 'front', className: 'blocks-corner-front', src: asset('prop-toy-front') },
        ],
      },
      {
        id: 'studyCorner',
        action: 'study',
        slot: 'study',
        className: 'study-corner-object',
        initialState: 'idle',
        label: '学习书桌',
        layers: [
          { id: 'back', className: 'study-corner-back', src: asset('decor-wall-soft-furnishing') },
          { id: 'front', className: 'study-corner-front', src: asset('decor-wall-soft-furnishing') },
        ],
      },
    ],
    interactions: {
      feed: {
        objectId: 'foodBowl',
        phases: [
          { at: 0, state: 'full', stagePhase: 'approach' },
          { at: 600, state: 'eating', stagePhase: 'active' },
          { at: 4600, state: 'done', stagePhase: 'satisfied' },
        ],
        resetDelay: 5200,
      },
      bath: {
        objectId: 'bathTub',
        phases: [
          { at: 0, state: 'ready', stagePhase: 'approach' },
          { at: 600, state: 'bathing', stagePhase: 'active' },
          { at: 4600, state: 'done', stagePhase: 'satisfied' },
        ],
        resetDelay: 5200,
      },
      sleep: {
        objectId: 'sleepBed',
        phases: [
          { at: 0, state: 'open', stagePhase: 'approach' },
          { at: 600, state: 'resting', stagePhase: 'active' },
          { at: 4600, state: 'done', stagePhase: 'satisfied' },
        ],
        resetDelay: 5200,
      },
      play: {
        objectId: 'toyBox',
        phases: [
          { at: 0, state: 'ready', stagePhase: 'approach' },
          { at: 600, state: 'playing', stagePhase: 'active' },
          { at: 4600, state: 'done', stagePhase: 'satisfied' },
        ],
        resetDelay: 5200,
      },
      pet: {
        objectId: 'heartSpot',
        phases: [
          { at: 0, state: 'ready', stagePhase: 'approach' },
          { at: 600, state: 'petting', stagePhase: 'active' },
          { at: 4600, state: 'done', stagePhase: 'satisfied' },
        ],
        resetDelay: 5200,
      },
      watchAnime: {
        objectId: 'mediaCorner',
        phases: [
          { at: 0, state: 'ready', stagePhase: 'approach' },
          { at: 600, state: 'watching', stagePhase: 'active' },
          { at: 4600, state: 'done', stagePhase: 'satisfied' },
        ],
        resetDelay: 5200,
      },
      playSwitch: {
        objectId: 'switchCorner',
        phases: [
          { at: 0, state: 'ready', stagePhase: 'approach' },
          { at: 600, state: 'gaming', stagePhase: 'active' },
          { at: 4600, state: 'done', stagePhase: 'satisfied' },
        ],
        resetDelay: 5200,
      },
      buildBlocks: {
        objectId: 'blocksCorner',
        phases: [
          { at: 0, state: 'ready', stagePhase: 'approach' },
          { at: 600, state: 'building', stagePhase: 'active' },
          { at: 4600, state: 'done', stagePhase: 'satisfied' },
        ],
        resetDelay: 5200,
      },
      study: {
        objectId: 'studyCorner',
        phases: [
          { at: 0, state: 'ready', stagePhase: 'approach' },
          { at: 600, state: 'studying', stagePhase: 'active' },
          { at: 4600, state: 'done', stagePhase: 'satisfied' },
        ],
        resetDelay: 5200,
      },
    },
  };
}());
