const { contextBridge, ipcRenderer } = require('electron');

const api = {
  // ===== 原有扁平方法（向后兼容） =====
  listPets: () => ipcRenderer.invoke('pets:list'),
  importPet: () => ipcRenderer.invoke('pet:import'),
  getWeather: () => ipcRenderer.invoke('weather:get'),
  generateYoyoLine: (payload) => ipcRenderer.invoke('ai:yoyo-line', payload),
  aiStatus: () => ipcRenderer.invoke('ai:status'),
  getDailyNews: (options) => ipcRenderer.invoke('news:get', options),
  getBounds: () => ipcRenderer.invoke('window:get-bounds'),
  moveBy: (delta) => ipcRenderer.invoke('window:move-by', delta),
  getMousePosition: () => ipcRenderer.invoke('mouse:getPosition'),
  setIgnoreMouse: (ignore) => ipcRenderer.invoke('window:set-ignore-mouse', ignore),
  setPosition: (pos) => ipcRenderer.invoke('pet:setPosition', pos),
  getPosition: () => ipcRenderer.invoke('pet:getPosition'),
  scanWindows: () => ipcRenderer.invoke('windows:scan'),
  showContextMenu: () => ipcRenderer.invoke('context-menu:show'),
  triggerEffect: (type) => ipcRenderer.invoke('effect:fullscreen', type),
  triggerCloneEffect: () => ipcRenderer.invoke('effect:clone'),
  triggerGiantEffect: () => ipcRenderer.invoke('effect:giant'),
  triggerCookEffect: () => ipcRenderer.invoke('effect:cook'),
  triggerWatchTvEffect: () => ipcRenderer.invoke('effect:watch-tv'),
  triggerPlaySwitchEffect: () => ipcRenderer.invoke('effect:play-switch'),
  openHome: () => ipcRenderer.invoke('home:open'),
  getLife: () => ipcRenderer.invoke('life:get'),
  getLifeActions: () => ipcRenderer.invoke('life:actions'),
  careForYoyo: (action) => ipcRenderer.invoke('life:care', action),
  setActiveVisual: (payload) => ipcRenderer.invoke('pet:setActiveVisual', payload),
  onMenuAction: (callback) => ipcRenderer.on('menu-action', (_e, action) => callback(action)),
  onLifeChanged: (callback) => ipcRenderer.on('life:changed', (_e, data) => callback(data)),
  onLifeCareFeedback: (callback) => ipcRenderer.on('life:care-feedback', (_e, data) => callback(data)),
  onAction: (callback) => ipcRenderer.on('action:pet', () => callback()),
  onWhip: (callback) => ipcRenderer.on('action:whip', () => callback()),
  onDance: (callback) => ipcRenderer.on('action:dance', (_e, checked) => callback(checked)),
  onFollow: (callback) => ipcRenderer.on('action:follow', (_e, checked) => callback(checked)),
  onSleep: (callback) => ipcRenderer.on('action:sleep', (_e, checked) => callback(checked)),
  onSystemResume: (callback) => ipcRenderer.on('system:resume', () => callback()),
  onBusyReminder: (callback) => ipcRenderer.on('system:busy-reminder', () => callback()),
  onManualEffect: (callback) => ipcRenderer.on('effect:manual', (_, data) => callback(data)),
  onKeyboardActivity: (cb) => ipcRenderer.on('keyboard:activity', (_e, data) => cb(data)),
  onActiveAppChanged: (callback) => ipcRenderer.on('active-app-changed', (_, data) => callback(data)),
  syncMenuState: (state) => ipcRenderer.send('menu-state:sync', state),
  onSettingsChanged: (callback) => ipcRenderer.on('settings-changed', (_, data) => callback(data)),
  onSettingsReset: (callback) => ipcRenderer.on('settings-reset', () => callback()),
  onBehaviorPreferencesReset: (callback) => ipcRenderer.on('behavior-preferences-reset', () => callback()),
  onOutfitChange: (cb) => ipcRenderer.on('outfit:change', (e, category, itemId) => cb(category, itemId)),
  onOutfitPreset: (cb) => ipcRenderer.on('outfit:preset', (e, presetId) => cb(presetId)),
  onOutfitRandom: (cb) => ipcRenderer.on('outfit:random', () => cb()),
  onOutfitReset: (cb) => ipcRenderer.on('outfit:reset', () => cb()),
  storeLoad:  ()          => ipcRenderer.invoke('store:load'),
  storeSet:   (key, val)  => ipcRenderer.invoke('store:set', key, val),
  storeBatch: (updates)   => ipcRenderer.invoke('store:batch', updates),
  behaviorDebugEnabled: () => ipcRenderer.invoke('debug:behavior-enabled'),
  desktopRunTestEnabled: () => ipcRenderer.invoke('debug:desktop-run-test-enabled'),
  live2dDemoEnabled: () => ipcRenderer.invoke('debug:live2d-demo-enabled'),
  debugLog: (type, payload) => ipcRenderer.send('debug:log', type, payload),
  debugLogPath: () => ipcRenderer.invoke('debug:log-path'),

  // ===== 命名空间分组（新代码推荐使用） =====
  effects: {
    trigger: (type) => ipcRenderer.invoke('effect:fullscreen', type),
    clone: () => ipcRenderer.invoke('effect:clone'),
    giant: () => ipcRenderer.invoke('effect:giant'),
    cook: () => ipcRenderer.invoke('effect:cook'),
    watchTv: () => ipcRenderer.invoke('effect:watch-tv'),
    playSwitch: () => ipcRenderer.invoke('effect:play-switch'),
    onManual: (cb) => ipcRenderer.on('effect:manual', (_, data) => cb(data)),
  },
  store: {
    load:  ()          => ipcRenderer.invoke('store:load'),
    set:   (key, val)  => ipcRenderer.invoke('store:set', key, val),
    batch: (updates)   => ipcRenderer.invoke('store:batch', updates),
  },
  life: {
    get: () => ipcRenderer.invoke('life:get'),
    actions: () => ipcRenderer.invoke('life:actions'),
    care: (action) => ipcRenderer.invoke('life:care', action),
    onChanged: (cb) => ipcRenderer.on('life:changed', (_e, data) => cb(data)),
    onCareFeedback: (cb) => ipcRenderer.on('life:care-feedback', (_e, data) => cb(data)),
  },
  window: {
    getBounds: () => ipcRenderer.invoke('window:get-bounds'),
    moveBy: (delta) => ipcRenderer.invoke('window:move-by', delta),
    setIgnoreMouse: (ignore) => ipcRenderer.invoke('window:set-ignore-mouse', ignore),
    scanWindows: () => ipcRenderer.invoke('windows:scan'),
  },
  pet: {
    setPosition: (pos) => ipcRenderer.invoke('pet:setPosition', pos),
    getPosition: () => ipcRenderer.invoke('pet:getPosition'),
    setActiveVisual: (payload) => ipcRenderer.invoke('pet:setActiveVisual', payload),
    listPets: () => ipcRenderer.invoke('pets:list'),
    importPet: () => ipcRenderer.invoke('pet:import'),
  },
};

contextBridge.exposeInMainWorld('petApi', api);
